### PR TITLE
Habeebah js assignment 2 - Boolean

### PR DESCRIPTION
**Pull request by queenhabeebah**

### CODE REVIEW

**Review by Adesoji1 — APPROVED** [review]
Good work!

**Review by Adesoji1 — CHANGES_REQUESTED** [review]
you only renamed the files, nothing was commited, kindly vet @queenhabeebah

**Review by Adesoji1 — APPROVED** [review]
Good!

**Comment by queenhabeebah** [comment]
> you only renamed the files, nothing was commited, kindly vet @queenhabeebah here but you have completed this task on 5th July 2024

Yes, I created a folder to put all the files together in it. Please, what should I do next?

**Pull request merged**
