### PR TITLE
CSS Assignment #1

### PR DESCRIPTION
**Pull request by njaumatilda**
I am ready for a review, but I am not fully confident about these flexbox concepts. If it is possible, I would like to have some more assignments on flexbox.

### CODE REVIEW

**Review by burrowdown — APPROVED** [review]
I'm sorry you're not feeling confident, your work here is really good!

**Comment by njaumatilda** [comment]
Thanks; I will look for more materials to work on.
@Adesoji1 please don't merge my branch. I am not ready to close my pull request...

**Comment by Adesoji1** [comment]
> Thanks; I will look for more materials to work on. @Adesoji1 please don't merge my branch. I am not ready to close my pull request...

@njaumatilda duly noted

**Comment by njaumatilda** [comment]
With the help of the MDN Web Docs, I have understood the terms better and their application along the different axes, in conjunction with the live trials available in the notes! I went through the assignment again this time not guessing but knowing what I wanted to do. I am ready to close my pull request now.

**Pull request merged**
