### PR TITLE
Css2-Assignment-grid-Ayo

### PR DESCRIPTION
**Pull request by Ayo-Mustapha155**
Dear Danny

Please find below for your attention in the Code Folder

Sub-folder: Grid
Assignment folder: Css2-Assignment-grid
Assignment files: index-css2.html
                            style-css2.css

Thank you
Regards

### CODE REVIEW

**Comment by Adesoji1** [comment]
@Ayo-Mustapha155  i have reviewed your assignment and it's a Good job well done.

**Review by Adesoji1 — APPROVED** [review]
Good work!

**Comment by Ayo-Mustapha155** [comment]
> Good work!

Thank you

**Comment by burrowdown** [comment]
Hey, it looks like this one still hasn't been merged, before you do @Ayo-Mustapha155  did you mean to remove the flexbox assignment? Do you want to delete that from this branch?

**Comment by Ayo-Mustapha155** [comment]
Hello Danny and Soji

I apologise for the delay to responding. We have had challenges with power in my area and, my back-up devices have also been exhausted. That is partly why I am running behind. Last time I checked, it looked like you have made that decision for me. I truly appreciate this. 

Again my apologies for the delay in responding.

**Pull request closed without merging**
