### PR TITLE
Sammykareem web APIs assignment

### PR DESCRIPTION
**Pull request by Kareem-Samad900**

### CODE REVIEW

**Comment by Adesoji1** [comment]
@Kareem-Samad900  
Screenshot from 2024-09-04 21-55-22
@Kareem-Samad900  the error you had is in the image and i resolved it, please take note of this next time, but so far all your work looks great, keep it up.

**Review by Adesoji1 — APPROVED** [review]
!Good work

**Review by Adesoji1 — APPROVED** [review]
!Good Work

**Comment by Kareem-Samad900** [comment]
Thank you for the correction. lesson learnt!

**Pull request merged**
