### PR TITLE
Jemitigo flexbox assignment submission

### PR DESCRIPTION
**Pull request by jemitigo**

### CODE REVIEW

**Comment by burrowdown** [comment]
You made these files inside your 'html-assignment' folder, which means these files will conflict with your old assignment. 

You skipped over the requirement from the beginning of the course to make a `code` folder and put a README.md in it. If you had done it, you would have a code folder to place your assignments in. Your file structure should look like this

- 0-getting-ready
-- (stuff I put in here and you don't change)
- 1-html-css
-- (stuff I put in here and you don't change)
- code
-- html-assignment
--- index.html
--- style.css
-- flexbox-assignment
--- index.html
--- style.css

**Comment by burrowdown** [comment]
The markdown assignment you missed can be found in the Week 2 video titled "Git Review & Markdown"

**Comment by Adesoji1** [comment]
@jemitigo kindly follow @burrowdown 's recommendation. This PR is closed, kindly open another.

**Comment by burrowdown** [comment]
Looks great! Ready to merge!

**Pull request merged**
