### PR TITLE
html-css-files

### PR DESCRIPTION
**Pull request by Eguagiebless**
Why cant we pull it from git directly.

### CODE REVIEW

**Comment by Adesoji1** [comment]
> Why cant we pull it from git directly.

@Eguagiebless what exactly do you want to pull, kindly explain further.Thank you.

**Comment by Eguagiebless** [comment]
> > Why cant we pull it from git directly.
> 
> @Eguagiebless what exactly do you want to pull, kindly explain further.Thank you.

my html css branch. Why cant we just do git pull on the terminal.

**Review by burrowdown — APPROVED** [review]
Looks good

**Comment by burrowdown** [comment]
I think I understand your question. Maybe you have already understood since you submitted this, but the answer is that a "git pull" and a "pull request" are totally unrelated concepts. A pull will move changes from the remote repository (that's here on GitHub) to your local repository (the one you access through your terminal.) It's the opposite of a "git push", which moves changes from your computer onto GitHub.

The purpose of the Pull Request is to create a space for code review. You are "requesting" to merge these changes into your personal branch (even though, in reality, your personal branch is yours to edit as you wish and you don't need permission from me or Adesoji.) That creates this space on GitHub where we can leave comments like this one, or comment on specific lines of code, and either approve of your work or request changes.

**Pull request merged**
